# Generated by Django 3.0.7 on 2020-07-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200706_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='shoe_size',
            field=models.CharField(choices=[('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('10', 'Ten'), ('11', 'Eleven')], default='8', max_length=2),
        ),
    ]
