# Generated by Django 3.0.7 on 2020-07-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_shoe_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='shoes',
            field=models.ManyToManyField(blank=True, to='main_app.Shoe'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
