# Generated by Django 3.0.6 on 2020-07-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_shoe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shoe',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='shoe_size',
            field=models.CharField(choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='8', max_length=2),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
